# TODO(jlewi): Get rid of this Dockerfile and just use the tf_sample image.
# The sole reason for this Dockerfile is to try to reproduce the CUDA initialization errors we are seeing
# with the 375.51 drivers.
FROM 	 gcr.io/cloud-ml-service-private/cloud-ml-tensorflow-gpu:v1_0ga-375.20-cloud_ml_v2_20170626_0211_RC02
RUN mkdir -p /opt/cmle
COPY tf_sample/tf_smoke.py /opt/cmle/
ENTRYPOINT ["python", "/opt/cmle/tf_smoke.py"]